name: Vendo arquivos compartilhados entre Steps

on:
  workflow_dispatch:

jobs:
  entre-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do Ubuntu
        run: cat /etc/os-release
      
      - name: Exibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips" > mensagem.txt

      - name: Qualquer outra coisa
        run: ls -lha

      - name: Le conteudo do arquivo
        run: cat mensagem.txt